app:
  home: ${user.home}/application_detector
  logs: ${app.home}/logs
spring:
  application:
    name: game_detector
  datasource:
    url: jdbc:sqlite:${app.home}/game_detector.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-only
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  quartz:
    auto-startup: false
logging:
  file:
    name: ${app.logs}/application.log
  logback:
    rollingpolicy:
      file-name-pattern: ${app.logs}/application-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 90
  level:
    root: info
server:
  port: 8081