app:
  home: ${user.home}/application_detector/dev
  logs: ${app.home}/logs
spring:
  application:
    name: game_detector
  data:
    jdbc:
      dialect: mysql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/game_detector_dev
    name: game_detector_dev
  quartz:
    auto-startup: false
logging:
  file:
    name: "application"
  logback:
    rollingpolicy:
      file-name-pattern: ${app.logs}/application-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 90
  level:
    root: info
server:
  port: 8081
